{"@timestamp": "2025-06-11T06:51:45.273323Z", "service": {"name": "logging-integration-test", "version": "2.0.0", "environment": "development"}, "host": {"name": "unknown", "ip": "218.38.240.188"}, "log": {"level": "ERROR", "logger": "__main__", "thread": 30668, "process": 5560}, "message": "Test error handling", "error": {"type": "ZeroDivisionError", "message": "division by zero", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Project\\Online-evaluation\\backend\\test_enhanced_logging.py\", line 176, in test_error_logging\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}, "error_test": true, "error_type": "ZeroDivisionError"}
